Vadar/Models/pasajes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vadar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasajes
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string zona_de_ruta { get; set; }
        public System.DateTime fecha { get; set; }
        public int sobres_entregados { get; set; }
        public int sobres_recogidos { get; set; }
        public decimal monto { get; set; }
        public string descripcion { get; set; }
    }
}

Vadar/Controllers/pasajesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vadar.Models;
using System.Configuration;
using Rotativa;
using Rotativa.Options;

namespace Vadar.Controllers
{
    [Authorize(Roles = "Administrador, Jefa, Empleado")]
    public class pasajesController : Controller
    {
        private oficinaModels db = new oficinaModels();

        // GET: pasajes
        public ActionResult Index()
        {
            return View(db.pasajes.ToList());
        }

        [Authorize(Roles = "Administrador, Jefa")]

        // GET: pasajes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pasajes pasajes = db.pasajes.Find(id);
            if (pasajes == null)
            {
                return HttpNotFound();
            }
            return View(pasajes);
        }

        // GET: pasajes/Create
        public ActionResult Create()
        {
            // Obtener los nombres de la tabla Mensajeros
            var mensajerosNombres = db.Mensajeros.Select(m => m.Nombre).ToList();

            // Pasar los nombres a la vista
            ViewBag.MensajerosNombres = mensajerosNombres;

            return View();
        }


        // POST: pasajes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,zona_de_ruta,fecha,sobres_entregados,sobres_recogidos,monto,descripcion")] pasajes pasajes, string NombreSeleccionado)
        {
            if (ModelState.IsValid)
            {
                // Asigna el nombre seleccionado al modelo
                pasajes.nombre = NombreSeleccionado;

                db.pasajes.Add(pasajes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // En caso de un modelo no válido, vuelve a mostrar la vista con el mensaje de error
            return View(pasajes);
        }


        [Authorize(Roles = "Jefa,Administrador")]
        // GET: pasajes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pasajes pasajes = db.pasajes.Find(id);
            if (pasajes == null)
            {
                return HttpNotFound();
            }
            return View(pasajes);
        }

        [Authorize(Roles = "Jefa,Administrador")]
        // POST: pasajes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nombre,zona_de_ruta,fecha,sobres_entregados,sobres_recogidos,monto,descripcion")] pasajes pasajes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pasajes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pasajes);
        }

        [Authorize(Roles = "Administrador, Jefa")]
        // GET: pasajes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            pasajes pasajes = db.pasajes.Find(id);
            if (pasajes == null)
            {
                return HttpNotFound();
            }
            return View(pasajes);
        }

        [Authorize(Roles = "Jefa,Administrador")]
        // POST: pasajes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            pasajes pasajes = db.pasajes.Find(id);
            db.pasajes.Remove(pasajes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrador, Jefa, Empleado")]
        // GET: pasajes/Search
        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrador, Jefa, Empleado")]
        public ActionResult Search(string nombre, DateTime fechaInicio, DateTime fechaFin)
        {
            // Llamar al procedimiento almacenado y obtener los resultados
            var results = db.Database.SqlQuery<pasajes>("exec sp_GetPasajesByNombreAndFecha @Nombre, @FechaInicio, @FechaFin",
                new SqlParameter("Nombre", nombre),
                new SqlParameter("FechaInicio", fechaInicio),
                new SqlParameter("FechaFin", fechaFin)).ToList();

            // Renderiza la vista Index como una vista parcial para PDF
            var pdfResult = new ViewAsPdf("VerPasajes", results)
            {
                FileName = "resultados_busqueda.pdf", // Nombre del archivo PDF
                PageSize = Size.A4,
                PageMargins = { Left = 10, Right = 10, Top = 10, Bottom = 10 },
            };

            return pdfResult;
        }


        [Authorize(Roles = "Administrador, Jefa")]
        public ActionResult VerPasajes()
        {
            // Aquí puedes obtener la lista de pasajes que deseas mostrar en la vista VerPasajes.
            var pasajesList = db.pasajes.ToList();

            return View("VerPasajes", pasajesList);
        }

    }
}

Vadar/Views/pasajes/Create.cshtml
@model Vadar.Models.pasajes

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link href="~/Estilos/Formularios.css" rel="stylesheet" type="text/css" />
</head>
<body>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Crear Pasajes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("nombre", "Nombre:", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @* Utiliza un dropdown para mostrar los nombres de Mensajeros *@
            @Html.DropDownList("NombreSeleccionado", new SelectList(ViewBag.MensajerosNombres), "Seleccione un nombre", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>


        <div class="form-group">
            @Html.LabelFor(model => model.zona_de_ruta, "Zona De Ruta:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zona_de_ruta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zona_de_ruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha, "Fecha:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <!-- Utilizar el control de entrada de fecha (input type="date") -->
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sobres_entregados, "Sobres Entregados:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sobres_entregados, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sobres_entregados, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sobres_recogidos, "Sobres Recogidos:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sobres_recogidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sobres_recogidos, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.monto, "Monto:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, "Descripcion:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Vadar/Views/pasajes/Delete.cshtml
@model Vadar.Models.pasajes

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>pasajes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zona_de_ruta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zona_de_ruta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sobres_entregados)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sobres_entregados)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sobres_recogidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sobres_recogidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.monto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Vadar/Views/pasajes/Details.cshtml
@model Vadar.Models.pasajes

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>pasajes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zona_de_ruta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zona_de_ruta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sobres_entregados)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sobres_entregados)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sobres_recogidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sobres_recogidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.monto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Vadar/Views/pasajes/Edit.cshtml
@model Vadar.Models.pasajes

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>pasajes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zona_de_ruta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zona_de_ruta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zona_de_ruta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sobres_entregados, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sobres_entregados, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sobres_entregados, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sobres_recogidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sobres_recogidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sobres_recogidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.monto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Vadar/Views/pasajes/Index.cshtml
@model IEnumerable<Vadar.Models.pasajes>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/Estilos/boton.css" />

<h2>Index</h2>

<p>
    <button type="button" class="btn" onclick="location.href='@Url.Action("Create")'">Crear Nuevo</button>
    <button type="button" class="btn" onclick="location.href='@Url.Action("VerPasajes", "pasajes")'">Ver Pasajes</button>
    <button type="button" class="btn" onclick="location.href='@Url.Action("Search", "pasajes")'">Buscar Pasajes</button>

    <h4>Solo el personal autorizado tiene acceso a ver todos los datos registrados, si se equivoca de dato porfavor consultar con Deidy o Gabriel</h4>

    <img src="~/Imagenes/cbe4.jpg" alt="Descripción de la imagen" style="max-width: 50%; height: auto;">

</p>

Vadar/Views/pasajes/Search.cshtml
@model Vadar.Models.pasajes

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Buscar</h2>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link href="~/Estilos/form.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <h4>Buscar Pasajes</h4>

    @using (Html.BeginForm("Search", "pasajes", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.Label("Nombre", new { @class = "control-label" })
            @Html.TextBox("nombre", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.nombre)
        </div>

        <div class="form-group">
            @Html.Label("Fecha de Inicio", new { @class = "control-label" })
            @Html.TextBox("fechaInicio", null, new { @class = "form-control", @type = "date" })
        </div>

        <div class="form-group">
            @Html.Label("Fecha de Fin", new { @class = "control-label" })
            @Html.TextBox("fechaFin", null, new { @class = "form-control", @type = "date" })
        </div>

        <button type="submit" class="btn-default">Buscar</button>
    }
    <h4>Puedes buscar tu pasaje por fechas especificas para generar un reporte en pdf de tus pasajes no te olvides que tu nombre debe ser el mismo de siempre resperando las mayusculas</h4>
</body>
</html>

Vadar/Views/pasajes/VerPasajes.cshtml
@model IEnumerable<Vadar.Models.pasajes>

@{
    ViewBag.Title = "VerPasajes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ver </h2>

<table class="table">
        @Html.Partial("Table", Model)
</table>

Vadar/Views/pasajes/table.cshtml
@model IEnumerable<Vadar.Models.pasajes>

<link href="~/Estilos/tabla.css" rel="stylesheet" />
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.nombre)</th>
        <th>@Html.DisplayNameFor(model => model.zona_de_ruta)</th>
        <th>Fecha</th>
        <th>@Html.DisplayNameFor(model => model.sobres_entregados)</th>
        <th>@Html.DisplayNameFor(model => model.sobres_recogidos)</th>
        <th>@Html.DisplayNameFor(model => model.monto)</th>
        <th>@Html.DisplayNameFor(model => model.descripcion)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.nombre)</td>
            <td>@Html.DisplayFor(modelItem => item.zona_de_ruta)</td>
            <td style="white-space: nowrap;">@item.fecha.ToString("yyyy-MM-dd")</td>
            <td>@Html.DisplayFor(modelItem => item.sobres_entregados)</td>
            <td>@Html.DisplayFor(modelItem => item.sobres_recogidos)</td>
            <td>@Html.DisplayFor(modelItem => item.monto)</td>
            <td>@Html.DisplayFor(modelItem => item.descripcion)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }
</table>